### ISSUE TITLE
View Single Reservation

### ISSUE THREAD

**Issue by joeypetrone** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#47]
## User Story
- [x] As a user I should be able to assign staff members to reservations.
- [x] As a user there should be some way to tell if a reservation has all the staff they need (waiter, bar tender, bus boy, etc.)
- [x] As a user I should be able to assign a table to a reservation.
- [x] As a user I should only be able to assign a table with the appropriate number of seats for that party (ie a reservation for 4 should not be assigned to a table with 2 seats).
- [x] As a user I should be able to view a single reservation page that displays all the information about that reservation.

## AC 
WHEN the user clicks on the view Single Reservations button 
THEN they should see a reprinted page with the selected reservation
AND they should see all the selected reservation's data
AND I should an option to assign staff, view assigned staff, and assign a table

## Dev Notes
+ create a click event for the single Reservations view button that hides all reservation tables and reprints the DOM with only the selected Reservation
+ the single Reservation view will display a form that shows reservation details. The Party name, time slot, and number of guests will not be editable
+ add drop downs for Servers and server assistants respectively. Populate these dropdowns with the response data from ```getStaffByJobId(job1)``` and ```getStaffByJobId(job6)``` respectively
+ add drop down for Tables that is populated by ```getTables``` that lists tables by tableId
+ add a conditional on the returned array from ```getTables``` that only prints the table if the ```tableId.numOfSeats``` is = or < the ```reservation.numOfGuests```
+ if reservation.numOfGuests is larger than the largest table (8?) then trigger an toast alert that says "too many guests" 
+ The form will also display a  'rejectReservation' button that calls the deleteReservation function and should be used if the "too many guests" alert shows up - clicking this reject button should also exit the single reservation view
+ The form will also display a submit button to edit the reservation details. When the submit button is clicked it will trigger a click event called ```editReservation``` that calls ```editEntireReservation``` to submit the modified reservation object - it will also exit the single reservation view and reprint the all reservations by date view viewing today's date

**Comment by John-Fleming** [comment]
![image](https://user-images.githubusercontent.com/51543096/80285771-cf819000-86ec-11ea-9f47-d3ce7986e2a8.png)
