### ISSUE TITLE
Orders

### ISSUE THREAD

**Issue by joeypetrone** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#48]
# User Story
- [x] As a user I should be able to assign menu items to reservations
- [x] As a user I should not be able to assign a menu item to a reservation if any of the ingredients from that menu item are sold out.
- [x] As a user I should be able to create a final bill for each reservation. This bill should show up on the single reservation pages.

# AC
WHEN the page loads
THEN I should see all menu items displayed by category, with Order container at the top
AND when I click an ```add-item``` button on an individual item, a copy appears in the Order container

#DEV NOTES
+ A click event called ```editOrderPage``` takes in the reservationId from the targeted reservation and prints a new page with six div containers, one for each category of menu item (appetizer, beverage, salad, main, dessert, Order), with the name of the category at the top of the div.
+ When an item is added (via click event on the menuItem) to the Order, it creates a function called ```newSingleOrder``` which creates a new Order object with the selected menuItemId, (closest card id) as well as the reservationId, and the ```singleOrderTotal: menuItem.price``` 
+ Page is reprinted with a copy of the menuItems now in the Order div, and a delete button is added to the copied menuItem card

**Comment by John-Fleming** [comment]
![image](https://user-images.githubusercontent.com/51543096/80287131-520e4d80-86f5-11ea-9918-4657e4e969b5.png)
