### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by joeypetrone** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#50]

**Comment by joeypetrone** [comment]
[LeBaguetteERD.pdf](https://github.com/nss-evening-cohort-11/nutshell-stormtroopers-jedis/files/4533132/LeBaguetteERD.pdf)

**Comment by joeypetrone** [comment]
![image](https://user-images.githubusercontent.com/59629666/80282715-b373f380-86d8-11ea-9eaa-93f2a7bcb832.png)

**Comment by joeypetrone** [comment]
![image](https://user-images.githubusercontent.com/59629666/80282737-ca1a4a80-86d8-11ea-8979-c8deec7a95fb.png)

**Comment by John-Fleming** [comment]
![Screen Shot 2020-04-25 at 9 51 27 AM](https://user-images.githubusercontent.com/51543096/80283022-6002a500-86da-11ea-8ffa-25f65d641036.png)
