### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by joeypetrone** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#51]

**Comment by StevenZelenak** [comment]
![image](https://user-images.githubusercontent.com/57852913/80050924-84912e00-84dc-11ea-9acd-f61383dbf30e.png)

**Comment by StevenZelenak** [comment]
![image](https://user-images.githubusercontent.com/57852913/80050945-9246b380-84dc-11ea-9721-564efbe65696.png)

**Comment by StevenZelenak** [comment]
![image](https://user-images.githubusercontent.com/57852913/80050974-9d99df00-84dc-11ea-94d4-47ce3fb069b3.png)

**Comment by StevenZelenak** [comment]
![image](https://user-images.githubusercontent.com/57852913/80050999-a985a100-84dc-11ea-9970-85cc404f2228.png)
