### ISSUE TITLE
Reporting: Revenue

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#52]
- [x] As a user I want to be able to see what the total revenue is for my restaurant since I opened.
- [x] As a user I want to be able to see what the revenue is for my restaurant over a 7 day period.
- [x] As a user I want to be able to see what the revenue is for my restaurant over a particular day.

## AC
WHEN the page loads
THEN I should be able to see two dropdowns to select a date range 
AND I should see four buttons for revenue, ingredients, top ten best menu items, top ten worst menu items
AND when I select a data range and click the button for revenue I should see total revenue for that particular range

## DEV NOTES
+ Create a click event on the revenue button with a class ```get-revenue```
+ create a ```getReservationsByDateRange```
+ Get selected date from dropdown menu and assign it to a ```const selectedDate```
+ create a ```let domString = '';```
+ Trigger smash function with a ```new Promise``` that retrieves all ```timeSlots``` by ```timeSlotId``` and puts them into an array called ```timeSlotArray``` 
+ compare the ```timeSlot.time``` with the ```selectedDate``` and save that to ```selectedDateArray```
+ retrieve all Reservations via ```getReservations```
+ Iterate over the array with ```forEach``` using a ```selectedDateArray.filter``` method to filter the matching ```timeSlotId``` between ```timeSlot``` and ```reservations``` and put the ```reservation.timeSlotId```s  in ```sortedReservations``` 
+ return ```sortedReservations```

**Comment by AaronLain** [comment]
https://momentjs.com/docs/#/displaying/difference/

https://gist.github.com/onildoaguiar/6cf7dbf9e0f0b8684eb5b0977b40c5ad

REFERENCE: sorting dates with moment.js

**Comment by joeypetrone** [comment]
Here is a date picker that uses bootstrap:
https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by AaronLain** [comment]
tack this on the end later for some reason

+ set ```domString``` equal to ```pareseInt(allBillTotal)```
+ return ```domString```
