### ISSUE TITLE
View All Reservations by Date

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#56]
## User Story
Whattever Joey can fix this
## AC
WHEN the page loads, I should see a date/calendar dropdown 
THEN when a date is selected, the page will reprint with all the specific reservations for that particular day
AND the table of reservations should display party name, time slot, whether the reservation has staff assigned or not, and two buttons that allow you to view a single reservation and edit an order for a single reservation
## Dev Notes
+ Use bootstrap or whatever
+ use and other calendar drop down from the reporting page
+ create a ```getReservationsBySingleDate```
+ Get selected date from dropdown menu and assign it to a ```const selectedDate```
+ create a ```let domString = '';```
+ Trigger smash function with a ```new Promise``` that retrieves all ```timeSlots``` by ```timeSlotId``` and puts them into an array called ```timeSlotArray``` 
+ compare the ```timeSlot.time``` with the ```selectedDate``` and save that to ```selectedDateArray```
+ retrieve all Reservations via ```getReservations```
+ Iterate over the array with ```forEach``` using a ```selectedDateArray.filter``` method to filter the matching ```timeSlotId``` between ```timeSlot``` and ```reservations``` and put the ```reservation.timeSlotId```s  in ```sortedReservations```
+ return ```sortedReservations```

+ write another function called ```printSingleReservationsByDate```  then ```forEach``` over sortedReservations``` and print each reservation to the domString with the necessary object key values to display the party name, time slot, and the boolean for fullyStaffed

**Comment by John-Fleming** [comment]
![image](https://user-images.githubusercontent.com/51543096/80285494-0656a680-86eb-11ea-9869-6ca6f72d9c23.png)
