### ISSUE TITLE
Show Reservation Receipt

### ISSUE THREAD

**Issue by John-Fleming** [nss-evening-cohort-11/nutshell-stormtroopers-jedis#59]
## USER STORY
As a user, when I view a single Reservation I should see a receipt with all items in my order plus the total bill amount.

## AC
WHEN I click the single Reservation view
THEN I should see an edit form
AND a receipt in its own column div next to the form
AND I should see everything ordered on the receipt plus the total amount for all menu items

## DEV NOTES
+ create a column div in the single reservation view with a value of col-4
+ get all Single Orders and put it in an array called ```allSingleOrders``` and sort by ```menuItemId```
+ get menuItems and put it in an array called ```allMenuItems``` and filter by the menuItemId's in the ```allSingleOrders```
+ forEach menuItem print the menuItem.name in the receipt
+ add together the ```singleOrderTotals``` and print the result at the bottom of said receipt

**Comment by joeypetrone** [comment]
Receipt Example: 
[Receipt Example](https://img.glyphs.co/img?src=aHR0cHM6Ly9zMy5tZWRpYWxvb3QuY29tL3Jlc291cmNlcy9SZWNlaXB0X0hUTUxfVGVtcGxhdGVfODAweDUxOC0xLnBuZw&q=90&enlarge=true&h=1036&w=1600)
